blog/urls.py
from django.urls import path

from .views import render_post, post_detail
app_name= 'blog'

urlpatterns = [
 
    path('', render_post, name="posts"),
    path('<int:post_id>', post_detail, name="post_detail" )
]

contacto/urls.py
from django.urls import path

from .views import contact

# app_name= 'contact'

urlpatterns = [

    path('', contact, name="contactos")
]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portafolioApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('aboutme/', views.about, name='aboutme'),
    path('blog/', include('blog.urls')),
    path('contact/', include('contacto.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


 

blog/models.py
from django.db import models
import datetime
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images', null=True, default="")
    image2 = models.ImageField(upload_to='blog/images/post',default="", blank=True)
    image3 = models.ImageField(upload_to='blog/images/post',default="", blank=True)
    image4 = models.ImageField(upload_to='blog/images/post',default="", blank=True)


    date = models.DateField(datetime.date.today)


    def __str__(self):
        return self.title

contacto/models.py
from django.db import models

# Create your models here.

portafolioApp/models.py
from django.db import models

# from django.db.models.fields import CharField
# from django.db.models.fields.files import ImageField
# Create your models here.

class Project(models.Model):

    title = models.CharField(max_length = 100)
    description = models.CharField(max_length = 250)
    image = models.ImageField(upload_to='portafolio/images')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def render_post(request):

    posts = Post.objects.all()
    return render(request, 'post.html', {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id) #pk : es el id de la publicacion
    
    post1 = Post.objects.all()
    return render(request, 'post_detail.html', {"post": post , "post1":post1 })

contacto/views.py
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from django.contrib import messages
from portafolio.settings import EMAIL_HOST_USER
# Create your views here.

def contact(request):
    if request.method== 'POST':
        subject = request.POST['subject']
        message = request.POST['message'] + " Direccion de correo " + request.POST['email'] + " De " + request.POST['name']
        from_email = EMAIL_HOST_USER
        
        # if subject and message and from_email:
        recipient_list= ['nowosadmarcos9@gmail.com']
        send_mail(subject,message, from_email, recipient_list)

        if request.method == 'POST':
            messages.success(request, "Thanks for contacting me")
            return redirect('contactos')
     
    return render(request, 'contact.html')

portafolioApp/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

def home(request):
    projects = Project.objects.all()


    return render(request, 'home.html', {"projects": projects})


def about(request):
    return render (request, 'partials/aboutme.html')

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div class="row" style="justify-content: center; flex-direction: row-reverse;">

        {% for post in posts %}
        <div class="contenedor-card col-md-4 col-sm-6 col-xs-12 d-flex justify-content-center my-2" >
                <div class="card color-card"  style="width: 18rem;  overflow: hidden;">
                    <div class="contendor-img card-img">
                        <img class="card-img-top img-card" src="{{post.image.url}}" alt="{{post.title}}" style="width: 100%;">
                    </div>
                    <div class="card-body">
                        <h4>{{post.title}}</h4> 
                        <!-- como interpretar un archivo html en el admin blog  |safe|-->
                        <p style="color:rgb(255,255,255,0.5);">{{post.description|striptags|truncatechars:50}}</p>
                        
                    </div>
                    <div class="card-footer" style="text-align: center;">
                        <a class="btn btn-warning" href="{% url 'blog:post_detail' post.id %}" >See</a>
                        <p>{{post.date|date:"N d Y"}}</p>
                    </div>
                </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="container my-5">

    <div class="row separador-blog">
        <div class="col-lg-12 blog-detail-1">
            
            <h1 style="text-transform: uppercase;">{{post.title}}</h1>
            <p class="paragraph-gral" style="text-decoration: underline;">Posted on {{post.date}}</p>
            <div style="display: flex; justify-content: center;">
                <img class="img-blog-detail" src="{{post.image.url}}" alt="{{post.title}}">
            </div>
            <div class="contenedor-paragraph" style="display: flex; justify-content: center; flex-direction: column;">
                <p>{{post.description|safe}}</p>
            </div>
            <div class=" section-blog my-2" style="width: 100%;" >
                {% if post.image2 %}
                <a href="{{post.image2.url}}" target="_blank"  style="width: 40%;">
                    <img class="img-card" src="{{post.image2.url}}" alt="{{post.title}}" style="width: 100%; border-radius: 5px;">
                </a>
                {% endif %}
                {% if post.image3 %}
                <a href="{{post.image3.url}}" target="_blank" style="width: 40%;">
                    <img class="img-card" src="{{post.image3.url}}" alt="{{post.title}}" style="width: 100%; border-radius: 5px;">
                </a>
                {% endif %}
                {% if post.image4 %}
                <a href="{{post.image4.url}}" target="_blank" style="width: 40%;">
                    <img class="img-card" src="{{post.image4.url}}" alt="{{post.title}}" style="width: 100%; border-radius: 5px;">
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

contacto/templates/contact.html
{% extends 'layout.html' %}

{% block content %}
    <div class="contenedor">
        <form class="form" action="{% url 'contactos' %}" method="post"> {% csrf_token %}

            <h1 class="title">Contact Me</h1>
            <div>
                <label for="Name">Name</label>
                <input class="form-control" type="text" name="name" id="Name" placeholder="Name">
            </div>
            <div>
                <label for="Subject">Subject</label>
                <input class="form-control" type="text" name="subject" id="Subject" placeholder="Subject">
            </div>
            <div>
                <label for="Email">Email</label>
                <input class="form-control" type="email" name="email" id="" placeholder="example@gmail.com">
            </div>
            <div>
                <label for="comment">Message</label>
                <textarea class="form-control comment" name="message" id="comment" cols="30" rows="5" ></textarea>
            </div>
            <div class="my-2 button-contact">
                <button class="btn btn-light button-animated font-weight" type="reset">Reset</button>
                <button class="btn btn-warning button-animated font-weight" type="submit">Submit</button>
            </div>
        </form>
    </div>

{% endblock %}

portafolioApp/templates/home.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

    <!-- Section Hero -->
    <div class="hero">

        <h1 class="title">Hi!<br><span class="span-name">I'm Marcos</span>Web Developer </h1>

        <a class="btn btn-warning button-home font-weight" href="#projects">Projects</a>
    </div>

    {% if request.path == 'aboutme' %} 
        {% include 'partials/aboutme.html' %}
    {% endif %}

    

    <!-- Skill -->

    <div class="container global">
        <div class="row">
            <h1 class="title" style="text-align: center;" >Skillset</h1>
            <div class="skills" >
                <div class="contenedor-img" style="text-align: center;">
                    <img class="img-skill" src="../static/img/skills/html.png" alt="">
                    <p>Html</p>
                </div>
                <div class="contenedor-img">
                    <img class="img-skill" src="../static/img/skills/css.png" alt="">
                    <p>Css</p>
                </div>
                <div class="contenedor-img">
                    <img class="img-skill" src="../static/img/skills/bootstrap.png" alt="">
                    <p>Bootstrap</p>
                </div>
                <div class="contenedor-img">
                    <img class="img-skill" src="../static/img/skills/python.png" alt="">
                    <p>Python</p>
                </div>
                <div class="contenedor-img">
                    <img class="img-skill" src="../static/img/skills/django.png" alt="">
                    <p>Django</p>
                </div>
                <div class="contenedor-img">
                    <img class="img-skill" src="../static/img/skills/postgresql.png" alt="">
                    <p>Postgresql</p>
                </div>
            </div>
        </div>
    </div>

    <!-- PROJECTS -->
    <div id="projects"></div>
    <div class="container-fluid index" >
        <h1 class="title">My Projects</h1>
        <div class="row" style="display: flex; justify-content: center;">
        {% for project in projects %}
            <div class="col-md-4 col-sm-6 col-xs-12 col-lg-4 d-flex justify-content-center my-2 p-4">
                <div class="card color-card card-project" style="width: 18rem; ">
                    <div class="">
                        <img class="card-img-top img-card" src="{{project.image.url}}" alt="{{project.title}}" >
                    </div>
                    <div class="card-body">
                        <h3 class="text-project">{{project.title}}</h3>

                        <p class="text-project">{{project.description}}</p>

                    </div>   
                    <div class="card-footer" style="display: flex; justify-content: center;">
                        {% if project.url %}
                            <a  class="btn btn-light" style="width: auto;" href="{{project.url}}" target="_blank">Link</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        {% endfor %}
        </div>
    </div>

{% endblock %}

portafolioApp/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Nowosad Marcos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- Importar iconos de bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
        <!-- Navbar -->
        {% include 'partials/navbar.html' %}

            <div class="container p-4 container-all">
                {% block content %}
              
                {% endblock %}
            </div>
            
        <!-- Footer -->
        {% include 'partials/footer.html' %}
        
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

portafolioApp/templates/partials/aboutme.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

    <!-- Section About Me -->
    <div id="about-me"></div>
    <section class="container about-me ">
        <h3 class="text-project">About Me</h3>
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <h3 class="h1-gral">Desarrollador Frontend</h3>
                <p class="paragraph-gral">Hola soy Nowosad Marcos</p>
                <p class="paragraph-gral">Estudiante de Ingeniería Informática que día a día esta enfocado en superarse y de rodearse de personas con el mismo deseo de conseguir sus metas. Por eso mismo estoy en la búsqueda de mi primer trabajo como desarrollador Frontend, donde pueda expresar mis ideas, desarrollar mis aptitudes y sobre todo dar lo mejor de mi para que la empresa pueda obtener increíbles mejoras en el ámbito social y económico. </p>
                <p class="paragraph-gral"> Unos de mis pasatiempos favoritos es el constante aprendizaje, gracias a eso, la programación se volvió unos de mis hobbies favoritos, porque todos los días tengo nuevos desafíos que superar, y esos desafíos siempre dejan algo en el cual yo puedo mejorar. Y considero que la empresa a la cual vaya a aplicar, el principal requisito que voy a observar por encima de todos, es si puedo aprender algo de ellos.</p>
                <div class="boton-about">
                    <a class="btn btn-warning button-home  font-weight" href="{% url 'contactos' %}">Contact Me</a>
                </div>
            </div>

            <div >
                
            </div>
        </div>
    </section>

{% endblock %}

portafolioApp/templates/partials/footer.html
{% load static %}



<div class="container-fluid" style="display: flex; justify-content: center;">

    <footer class="footer-border">
        <div class="d-flex flex-column flex-sm-row flex-sm-column flex-md-row aling-items-center justify-content-around py-4 mt-4 footer-content" style="gap: 15px;">
            <p class="paragraph-gral">© 2023 NowosadMarcos, Inc. All rights reserved.</p>
            <div>
                <!-- style="display: flex; gap: 5px; font-size: 15px; align-items: center;" -->
               <p class="paragraph-gral font-weight">nowosadmarcos9@gmail.com</p>
                <p class="paragraph-gral font-weight">+54 1133043610</p>
            </div>
            <ul class="list-unstyled d-flex">
                <a class="icon-style" href=""><span class="px-3" style="font-size: 24px; justify-content: space-;"><i class="bi bi-twitter icon"></i></span></a>
                <a class="icon-style" href="https://www.instagram.com/marcos_nowosad/" target="_blank"><span class="px-3" style="font-size: 24px;"><i class="bi bi-instagram icon"></i></span></a>
                <a class="icon-style" href="https://github.com/MarcosNowosad" target="_blank"><span class="px-3" style="font-size: 24px; " ><i class="bi bi-github icon"></i></span></a>
            </ul>
        </div>
    </footer>

</div>

portafolioApp/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg  navegacion" >
    <div class="container" style="display: flex; justify-content: space-between;">
        <a class="navbar-brand  text-project icon" href="/">Marcos</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-list" style="font-size: 30px; color: #ffc107;"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
                <li class="nav-item ">
                    <a class="nav-link {% if request.path == '/' %} active {% endif %}" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link  {% if request.path == '/aboutme/' %} active {% endif %}" href="{% url 'aboutme' %}">About Me</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link {% if request.path == '/blog/' %} active {% endif %} " href="{% url 'blog:posts' %}">Blog</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/contact/' %} active {% endif %} " href="{% url 'contactos' %}">Contact</a>
                </li>
            </ul>
            <div class="boton-nav">
                <a href="{% static 'portafolio/cv.pdf' %}" class="btn btn-warning button-animated font-weight" target="_blank">Download Resume</a>
                <!-- <button class="btn btn-outline-success font-weight" type="submit" >Search</button> -->
            </div>
        </div>
    </div>
</nav>